### ISSUE TITLE
mask :-)

### ISSUE THREAD

**Issue by ursbraem** [BenjaminBeck/bdm_kesearchindexer_flux#1]
Hi Benjamin

I just stumbled across this when searching for a 7.6 compatible ke_search indexer, awesome!

you wouldn't be interested in writing a similar indexer for ext:mask (TYPO3 7.6) as well, or would you? 😁 
I'm apparently unable to do it myself and am looking for someone to sponsor... 
cf https://forge.typo3.org/issues/78041# 

Cheers
Urs

**Comment by BenjaminBeck** [comment]
Hello Urs,
generally this is possible - but at the moment i do have a big project that consumes all my time.

Greetings 
Benjamin

**Comment by ursbraem** [comment]
Ok, cool! If you have a gap to fill, just let me know.
